package com.example.demo.service;

import com.example.demo.dao.AuthorDao;
import com.example.demo.model.Author;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;

@Service
public class AuthorService {
    // use fakeauthor for dependency injection

    private final AuthorDao authorDao;

    // author dao injected not directy generated by this class
    // qualifier for different implementations of interface
    @Autowired
    public  AuthorService(@Qualifier("fakeDao") AuthorDao authorDao){
        this.authorDao = authorDao;
    }

    public List<Author> getAuthors(){
        return authorDao.getAuthors();
    }

    public int addAuthor(Author author){
        return authorDao.insertAuthor(author);
    }

    public int addAuthor(Author author, UUID id){
        return authorDao.insertAuthor(id, author);
    }
}
